export const mockProducts = [
  // --- SINGLES (Pokémon) ---
  {
    id: 'charizard-ex-sv3',
    name: 'Charizard ex (Special Illustration Rare)',
    type: 'single',
    game: 'Pokémon',
    edition: 'Obsidian Flames',
    subsubcategory: 'Special Illustration',
    rarity: 'Special Illustration Rare',
    image: 'https://images.pokemontcg.io/sv3/223.png',
    backImage: 'https://images.pokemontcg.io/unbroken_bonds/back.png',
    desc: 'Jedna z nejcennějších karet ze setu Scarlet & Violet - Obsidian Flames. Karta zobrazuje Charizarda v jeho Tera krystalické podobě.',
    variants: [
      { id: 'ch-1', condition: 'NM', lang: 'EN', foil: true, price: 1850, stock: 3 },
      { id: 'ch-2', condition: 'EX', lang: 'EN', foil: true, price: 1600, stock: 1 },
      { id: 'ch-3', condition: 'NM', lang: 'JP', foil: true, price: 2100, stock: 2 }
    ]
  },
  {
    id: 'pikachu-vmax-swsh4',
    name: 'Pikachu VMAX (Rainbow Rare)',
    type: 'single',
    game: 'Pokémon',
    edition: 'Vivid Voltage',
    subsubcategory: 'Rainbow Rare',
    rarity: 'Rainbow Rare',
    image: 'https://images.pokemontcg.io/swsh4/188.png',
    backImage: 'https://images.pokemontcg.io/unbroken_bonds/back.png',
    desc: 'Ikonický „Fat Pikachu“ v duhovém provedení ze setu Vivid Voltage. Vyhledávaný sběratelský artikl.',
    variants: [
      { id: 'pk-1', condition: 'NM', lang: 'EN', foil: true, price: 3200, stock: 1 },
      { id: 'pk-2', condition: 'LP', lang: 'EN', foil: true, price: 2600, stock: 1 }
    ]
  },
  {
    id: 'umbreon-vmax-alt',
    name: 'Umbreon VMAX (Alternate Art Secret Rare)',
    type: 'single',
    game: 'Pokémon',
    edition: 'Evolving Skies',
    subsubcategory: 'Alternate Art Secret Rare',
    rarity: 'Alternate Art Secret Rare',
    image: 'https://images.pokemontcg.io/swsh7/215.png',
    backImage: 'https://images.pokemontcg.io/unbroken_bonds/back.png',
    desc: 'Legendární „Moonbreon“ z edice Evolving Skies. Karta s nejvyšším růstem ceny za poslední roky zobrazující Umbreona sahajícího po měsíci.',
    variants: [
      { id: 'um-1', condition: 'NM', lang: 'EN', foil: true, price: 19500, stock: 1 }
    ]
  },
  {
    id: 'giratina-v-alt',
    name: 'Giratina V (Alternate Art)',
    type: 'single',
    game: 'Pokémon',
    edition: 'Lost Origin',
    subsubcategory: 'Alternate Art',
    rarity: 'Alternate Art',
    image: 'https://images.pokemontcg.io/swsh11/186.png',
    backImage: 'https://images.pokemontcg.io/unbroken_bonds/back.png',
    desc: 'Nádherná a detailně ilustrovaná karta Giratiny z edice Lost Origin. Mistrovské dílo moderního TCG designu.',
    variants: [
      { id: 'gi-1', condition: 'NM', lang: 'EN', foil: true, price: 7900, stock: 2 },
      { id: 'gi-2', condition: 'EX', lang: 'EN', foil: true, price: 7100, stock: 1 }
    ]
  },
  {
    id: 'rayquaza-vmax-alt',
    name: 'Rayquaza VMAX (Alternate Art Secret Rare)',
    type: 'single',
    game: 'Pokémon',
    edition: 'Evolving Skies',
    subsubcategory: 'Alternate Art Secret Rare',
    rarity: 'Alternate Art Secret Rare',
    image: 'https://images.pokemontcg.io/swsh7/218.png',
    backImage: 'https://images.pokemontcg.io/unbroken_bonds/back.png',
    desc: 'Jedna z nejvyhledávanějších a nejkrásnějších karet moderní éry ze setu Evolving Skies zobrazující Rayquazu obtáčející se kolem věže.',
    variants: [
      { id: 'ra-1', condition: 'NM', lang: 'EN', foil: true, price: 14500, stock: 1 }
    ]
  },

  // --- SINGLES (Lorcana) ---
  {
    id: 'elsa-spirit-of-winter-enchanted',
    name: 'Elsa - Spirit of Winter (Enchanted)',
    type: 'single',
    game: 'Lorcana',
    edition: 'The First Chapter',
    subsubcategory: 'Enchanted',
    rarity: 'Enchanted',
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/508930_in_1000x1000.jpg',
    backImage: 'https://images.pokemontcg.io/unbroken_bonds/back.png',
    desc: 'Nádherná a extrémně vzácná Enchanted verze Elsy z první edice Disney Lorcana: The First Chapter. Sběratelský klenot s úchvatným foilovým efektem.',
    variants: [
      { id: 'el-1', condition: 'NM', lang: 'EN', foil: true, price: 12500, stock: 1 }
    ]
  },

  // --- SINGLES (One Piece) ---
  {
    id: 'luffy-gear-5-op05-alt',
    name: 'Monkey D. Luffy (Gear 5 Manga Alternate Art)',
    type: 'single',
    game: 'One Piece',
    edition: 'Awakening of the New Era',
    subsubcategory: 'Alternate Art',
    rarity: 'Alternate Art',
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/527633_in_1000x1000.jpg',
    backImage: 'https://images.pokemontcg.io/unbroken_bonds/back.png',
    desc: 'Jedna z nejlegendárnějších karet ze hry One Piece Card Game zobrazující Luffyho v jeho finální formě Gear 5 s manga pozadím.',
    variants: [
      { id: 'lf-1', condition: 'NM', lang: 'EN', foil: true, price: 42000, stock: 1 }
    ]
  },

  // --- SEALED PRODUCTS (Pokémon ENG) ---
  {
    id: 'stellar-crown-booster-box',
    name: 'Pokémon Scarlet & Violet - Stellar Crown Booster Box',
    type: 'sealed',
    game: 'Pokémon',
    edition: 'Stellar Crown',
    price: 3290,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/552309_in_1000x1000.jpg',
    lang: 'EN',
    subsubcategory: 'Draft Booster Box',
    packagingType: 'Booster Box',
    desc: 'Booster box chystané edice Stellar Crown. Obsahuje 36 booster balíčků po 10 kartách. Ideální pro sběratele a hráče.',
    stock: 50,
    boosterCount: 36,
    year: 2024,
    foilCondition: '100% stav',
    preorder: true
  },
  {
    id: 'pokemon-151-etb',
    name: 'Pokémon Scarlet & Violet - 151 Elite Trainer Box',
    type: 'sealed',
    game: 'Pokémon',
    edition: '151',
    price: 1399,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/506307_in_1000x1000.jpg',
    lang: 'EN',
    subsubcategory: 'Standard ETB',
    packagingType: 'Elite Trainer Box',
    desc: 'Elite Trainer Box (ETB) z oblíbené edice 151. Obsahuje 9 boosterů, promo kartu Snorlaxe, obaly na karty, kostky, žetony a sběratelského průvodce. Bezchybný stav krabice, ideální na sbírku.',
    stock: 8,
    boosterCount: 9,
    year: 2023,
    foilCondition: '100% stav',
    investment: true
  },
  {
    id: 'paldean-fates-bundle',
    name: 'Pokémon Scarlet & Violet - Paldean Fates Booster Bundle',
    type: 'sealed',
    game: 'Pokémon',
    edition: 'Paldean Fates',
    price: 649,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/530267_in_1000x1000.jpg',
    lang: 'EN',
    subsubcategory: 'Booster Bundle',
    packagingType: 'Booster Bundle',
    desc: 'Booster Bundle speciální edice Paldean Fates. Obsahuje 6 booster balíčků s možností vybalení vzácných Shiny Pokémonů.',
    stock: 24,
    boosterCount: 6,
    year: 2024,
    foilCondition: '100% stav'
  },
  {
    id: 'shrouded-fable-booster',
    name: 'Pokémon Scarlet & Violet - Shrouded Fable Booster Pack',
    type: 'sealed',
    game: 'Pokémon',
    edition: 'Shrouded Fable',
    price: 119,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/550201_in_1000x1000.jpg',
    lang: 'EN',
    subsubcategory: 'Standard Booster',
    packagingType: 'Booster',
    desc: 'Samostatný booster balíček ze speciální minisady Shrouded Fable. Obsahuje 10 náhodných karet.',
    stock: 120,
    boosterCount: 1,
    year: 2024,
    foilCondition: '100% stav'
  },
  {
    id: 'charizard-ex-super-premium-coll',
    name: 'Pokémon Scarlet & Violet - Charizard ex Super Premium Collection',
    type: 'sealed',
    game: 'Pokémon',
    edition: 'Scarlet & Violet',
    price: 1990,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/561990_in_1000x1000.jpg',
    lang: 'EN',
    subsubcategory: 'Premium Collection',
    packagingType: 'Special Collection',
    desc: 'Prémiová sběratelská kolekce věnovaná Charizardovi. Obsahuje exkluzivní figurku Charizarda, promo karty a 10 booster balíčků.',
    stock: 15,
    boosterCount: 10,
    year: 2024,
    foilCondition: '100% stav'
  },
  {
    id: 'pokemon-classic-case',
    name: 'Pokémon Classic Collection - Case',
    type: 'sealed',
    game: 'Pokémon',
    edition: 'Classic Collection',
    price: 24500,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/496229_in_1000x1000.jpg',
    lang: 'EN',
    subsubcategory: 'Sealed Case',
    packagingType: 'Other',
    desc: 'Originální case obsahující 2 kompletní sady Pokémon Classic Collection přímo od výrobce. Perfektní investiční produkt zajištěný originální páskou.',
    stock: 2,
    boosterCount: 0,
    year: 2023,
    foilCondition: '100% stav',
    investment: true
  },

  // --- SEALED PRODUCTS (Pokémon JPN) ---
  {
    id: 'pokemon-151-booster-box-jp',
    name: 'Pokémon Scarlet & Violet - 151 Booster Box (JPN)',
    type: 'sealed',
    game: 'Pokémon',
    edition: '151 JPN',
    price: 1790,
    originalPrice: 2690,
    image: '/Akce - NORTHVALE.webp',
    lang: 'JP',
    subsubcategory: 'Japanese Booster Box',
    packagingType: 'Booster Box',
    desc: 'Oblíbený japonský booster box edice 151. Obsahuje 20 booster balíčků po 7 kartách s garancí tajných vzácných karet a šancí na legendárního Mew ex.',
    stock: 5,
    boosterCount: 20,
    year: 2023,
    foilCondition: '100% stav'
  },
  {
    id: 'shiny-treasure-ex-box-jp',
    name: 'Pokémon Shiny Treasure ex Booster Box (JPN)',
    type: 'sealed',
    game: 'Pokémon',
    edition: 'Shiny Treasure ex',
    price: 1590,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/524823_in_1000x1000.jpg',
    lang: 'JP',
    subsubcategory: 'Japanese Booster Box',
    packagingType: 'Booster Box',
    desc: 'Japonský booster box speciálního High Class setu Shiny Treasure ex. Obsahuje 10 boosterů po 10 kartách s garancí ex karet a šancí na Shiny Pokémonů.',
    stock: 12,
    boosterCount: 10,
    year: 2023,
    foilCondition: '100% stav'
  },
  {
    id: 'shiny-treasure-single-pack-jp',
    name: 'Pokémon Shiny Treasure ex Booster Pack (JPN)',
    type: 'sealed',
    game: 'Pokémon',
    edition: 'Shiny Treasure ex',
    price: 169,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/524823_in_1000x1000.jpg',
    lang: 'JP',
    subsubcategory: 'Japanese Booster Pack',
    packagingType: 'Booster',
    desc: 'Japonský booster balíček ze setu Shiny Treasure ex. Obsahuje 10 karet.',
    stock: 60,
    boosterCount: 1,
    year: 2023,
    foilCondition: '100% stav'
  },
  {
    id: 'crimson-haze-special-set-jp',
    name: 'Pokémon Crimson Haze Special Set (JPN)',
    type: 'sealed',
    game: 'Pokémon',
    edition: 'Crimson Haze',
    price: 990,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/544321_in_1000x1000.jpg',
    lang: 'JP',
    subsubcategory: 'Japanese Special Set',
    packagingType: 'Special Collection',
    desc: 'Speciální dárkové balení z japonského setu Crimson Haze obsahující boostery a tematické herní příslušenství.',
    stock: 8,
    boosterCount: 8,
    year: 2024,
    foilCondition: '100% stav'
  },
  {
    id: 'masked-valiance-deck-shield-jp',
    name: 'Pokémon Deck Shield Ogerpon (JPN)',
    type: 'sealed',
    game: 'Pokémon',
    edition: 'Mask of Change',
    price: 249,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/122159_in_1000x1000.jpg',
    lang: 'JP',
    subsubcategory: 'Japanese Other',
    packagingType: 'Other',
    desc: 'Japonské originální obaly na karty (64 ks) s motivem Ogerpona z oficiálního Pokémon Center Japan.',
    stock: 14,
    boosterCount: 0,
    year: 2024,
    foilCondition: '100% stav'
  },

  // --- SEALED PRODUCTS (Pokémon CHN) ---
  {
    id: 'nine-colors-gather-booster-box-cn',
    name: 'Pokémon Nine Colors Gather Booster Box (CHN)',
    type: 'sealed',
    game: 'Pokémon',
    edition: 'Nine Colors Gather',
    price: 1990,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/506307_in_1000x1000.jpg',
    lang: 'CN',
    subsubcategory: 'Chinese Booster Box',
    packagingType: 'Booster Box',
    desc: 'Zjednodušený čínský booster box (Simplified Chinese) z edice Nine Colors Gather (ekvivalent Evolving Skies). Obsahuje 24 boosterů po 5 kartách.',
    stock: 10,
    boosterCount: 24,
    year: 2023,
    foilCondition: '100% stav'
  },
  {
    id: 'nine-colors-gather-pack-cn',
    name: 'Pokémon Nine Colors Gather Booster Pack (CHN)',
    type: 'sealed',
    game: 'Pokémon',
    edition: 'Nine Colors Gather',
    price: 89,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/550201_in_1000x1000.jpg',
    lang: 'CN',
    subsubcategory: 'Chinese Booster Pack',
    packagingType: 'Booster',
    desc: 'Čínský booster balíček z edice Nine Colors Gather. Obsahuje 5 náhodně namíchaných karet.',
    stock: 150,
    boosterCount: 1,
    year: 2023,
    foilCondition: '100% stav'
  },

  // --- SEALED PRODUCTS (Lorcana) ---
  {
    id: 'lorcana-first-chapter-booster-box',
    name: 'Disney Lorcana: The First Chapter - Booster Box',
    type: 'sealed',
    game: 'Lorcana',
    edition: 'The First Chapter',
    price: 4890,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/501783_in_1000x1000.jpg',
    lang: 'EN',
    subsubcategory: 'Standard Booster Box',
    packagingType: 'Booster Box',
    desc: 'Originální booster box obsahující 24 booster balíčků z první, dnes již legendární edice Disney Lorcana: The First Chapter. Sběratelsky vysoce žádané.',
    stock: 4,
    boosterCount: 24,
    year: 2023,
    foilCondition: '100% stav',
    investment: true
  },
  {
    id: 'lorcana-shimmering-skies-trove',
    name: 'Disney Lorcana: Shimmering Skies - Illumineer\'s Trove',
    type: 'sealed',
    game: 'Lorcana',
    edition: 'Shimmering Skies',
    price: 1390,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/559441_in_1000x1000.jpg',
    lang: 'EN',
    subsubcategory: "Illumineer's Trove",
    packagingType: 'Trove Box',
    desc: 'Illumineer\'s Trove z edice Shimmering Skies. Obsahuje 8 boosterů, krabičky na balíčky, kostky, počítadlo životů a sběratelskou krabici na karty.',
    stock: 8,
    boosterCount: 8,
    year: 2024,
    foilCondition: '100% stav'
  },
  {
    id: 'lorcana-rise-floodborn-booster',
    name: 'Disney Lorcana: Rise of the Floodborn - Booster Pack',
    type: 'sealed',
    game: 'Lorcana',
    edition: 'Rise of the Floodborn',
    price: 149,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/523991_in_1000x1000.jpg',
    lang: 'EN',
    subsubcategory: 'Standard Booster',
    packagingType: 'Booster',
    desc: 'Booster balíček z druhé edice Rise of the Floodborn. Obsahuje 12 náhodných karet.',
    stock: 80,
    boosterCount: 1,
    year: 2023,
    foilCondition: '100% stav'
  },
  {
    id: 'lorcana-starter-deck-ursula',
    name: 'Disney Lorcana: Ursula\'s Return - Starter Deck',
    type: 'sealed',
    game: 'Lorcana',
    edition: 'Ursula\'s Return',
    price: 490,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/552211_in_1000x1000.jpg',
    lang: 'EN',
    subsubcategory: 'Starter Deck',
    packagingType: 'Other',
    desc: 'Předpřipravený herní balíček o 60 kartách připravený k okamžitému hraní, obsahuje také 1 booster balíček.',
    stock: 20,
    boosterCount: 1,
    year: 2024,
    foilCondition: '100% stav'
  },

  // --- SEALED PRODUCTS (Ostatní TCG) ---
  {
    id: 'mtg-foundations-booster-box',
    name: 'Magic: The Gathering - Foundations Booster Box (36 balíčků)',
    type: 'sealed',
    game: 'Ostatní TCG',
    edition: 'Foundations',
    price: 3690,
    image: '/Logo_Ostatni_TCG.webp',
    lang: 'EN',
    subsubcategory: 'Standard Booster Box',
    packagingType: 'Booster Box',
    desc: 'Foundations je základní sada pro Magic: The Gathering. Tento displej obsahuje 36 Play boosterů.',
    stock: 8,
    boosterCount: 36,
    year: 2025,
    foilCondition: '100% stav'
  },
  {
    id: 'mtg-foundations-booster-pack',
    name: 'Magic: The Gathering - Foundations Play Booster Pack',
    type: 'sealed',
    game: 'Ostatní TCG',
    edition: 'Foundations',
    price: 119,
    image: '/Logo_Ostatni_TCG.webp',
    lang: 'EN',
    subsubcategory: 'Standard Booster Pack',
    packagingType: 'Booster',
    desc: 'Rozšiřující booster balíček z edice Foundations pro legendární karetní hru Magic: The Gathering.',
    stock: 75,
    boosterCount: 1,
    year: 2025,
    foilCondition: '100% stav'
  },
  {
    id: 'sw-unlimited-starter-deck',
    name: 'Star Wars: Unlimited - Spark of Rebellion Starter Deck (2 hráči)',
    type: 'sealed',
    game: 'Ostatní TCG',
    edition: 'Spark of Rebellion',
    price: 890,
    image: '/Logo_Ostatni_TCG.webp',
    lang: 'EN',
    subsubcategory: 'Standard Starter Deck',
    packagingType: 'Trial Deck',
    desc: 'Kompletní startovní sada pro dva hráče pro novou karetní hru Star Wars: Unlimited.',
    stock: 12,
    boosterCount: 0,
    year: 2024,
    foilCondition: '100% stav'
  },
  {
    id: 'tcg-playmat-neon-gold',
    name: 'Northvale Gold TCG Herní podložka (exkluzivní design)',
    type: 'sealed',
    game: 'Ostatní TCG',
    edition: 'Příslušenství',
    price: 690,
    image: '/Logo_Ostatni_TCG.webp',
    lang: 'EN',
    subsubcategory: 'Official Playmat',
    packagingType: 'Other',
    desc: 'Prémiová herní podložka z vysoce kvalitního neoprenu se zlatým lemováním a protiskluzovou spodní stranou.',
    stock: 4,
    boosterCount: 0,
    year: 2025,
    foilCondition: '100% stav'
  },

  // --- SEALED PRODUCTS (One Piece) ---
  {
    id: 'op-08-booster-box',
    name: 'One Piece Card Game: Two Legends Booster Box (OP-08)',
    type: 'sealed',
    game: 'One Piece',
    edition: 'Two Legends',
    price: 3490,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/544321_in_1000x1000.jpg',
    lang: 'EN',
    subsubcategory: 'English Booster Box',
    packagingType: 'Booster Box',
    desc: 'Předobjednávka anglického booster boxu OP-08 Two Legends. Obsahuje 24 boosterů po 12 kartách.',
    stock: 30,
    boosterCount: 24,
    year: 2024,
    foilCondition: '100% stav',
    preorder: true
  },
  {
    id: 'op-07-booster-pack',
    name: 'One Piece Card Game: 500 Years in the Future Booster Pack (OP-07)',
    type: 'sealed',
    game: 'One Piece',
    edition: '500 Years in the Future',
    price: 159,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/544320_in_1000x1000.jpg',
    lang: 'EN',
    subsubcategory: 'English Booster Pack',
    packagingType: 'Booster',
    desc: 'Rozšiřující booster balíček ze ságy Egghead (OP-07). Obsahuje 12 karet.',
    stock: 120,
    boosterCount: 1,
    year: 2024,
    foilCondition: '100% stav'
  },
  {
    id: 'op-starter-deck-luffy',
    name: 'One Piece Card Game: Starter Deck Monkey D. Luffy (ST-10)',
    type: 'sealed',
    game: 'One Piece',
    edition: 'Ultimate Deck',
    price: 790,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/542211_in_1000x1000.jpg',
    lang: 'EN',
    subsubcategory: 'Starter Deck',
    packagingType: 'Other',
    desc: 'Tento Ultimate Deck obsahuje silný předpřipravený balíček se 3 vůdčími kartami (Luffy, Law, Kid) v luxusním provedení.',
    stock: 15,
    boosterCount: 0,
    year: 2023,
    foilCondition: '100% stav'
  },

  // --- ACCESSORIES (Příslušenství) ---
  {
    id: 'dragon-shield-matte-clear',
    name: 'Dragon Shield Matte Clear (100 obalů)',
    type: 'accessory',
    game: 'Accessories',
    subcat: 'Sleeves',
    price: 249,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/122159_in_1000x1000.jpg',
    desc: 'Matné herní obaly (100 ks) standardní velikosti od značky Dragon Shield. Vynikající pro ochranu karet a skvělý pocit při míchání balíčku.',
    stock: 100
  },
  {
    id: 'penny-sleeves-100',
    name: 'Ultra Pro Soft Card Sleeves (Penny sleeves, 100ks)',
    type: 'accessory',
    game: 'Accessories',
    subcat: 'Sleeves',
    price: 39,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/95743_in_1000x1000.jpg',
    desc: 'Základní měkké obaly na ochranu karet před poškrábáním. Nezbytné pro ukládání karet do toploaderů.',
    stock: 500
  },
  {
    id: 'toploaders-25',
    name: 'Ultra Pro Toploader 3"x4" (25ks)',
    type: 'accessory',
    game: 'Accessories',
    subcat: 'Toploaders',
    price: 119,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/142981_in_1000x1000.jpg',
    desc: 'Pevné plastové toploadery na dražší sběratelské kousky. Poskytují vynikající ochranu před ohybem a poškozením rohů.',
    stock: 150
  },
  {
    id: 'ultra-pro-pro-binder-9-pocket',
    name: 'Ultra Pro 9-Pocket PRO-Binder (Černý)',
    type: 'accessory',
    game: 'Accessories',
    subcat: 'Binders',
    subsubcat: 'cards',
    price: 650,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/142827_in_1000x1000.jpg',
    desc: 'Prémiové album na 360 karet s elastickým páskem a bočním vkládáním pro maximální bezpečí tvé sbírky.',
    stock: 20
  },
  {
    id: 'binder-toploader',
    name: 'Toploader Binder album pro 216 karet v toploaderech',
    type: 'accessory',
    game: 'Accessories',
    subcat: 'Binders',
    subsubcat: 'toploaders',
    price: 890,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/142827_in_1000x1000.jpg',
    desc: 'Speciální album navržené pro bezpečné ukládání a prezentaci karet uložených v pevných toploaderech. Kapacita 216 slotů.',
    stock: 10
  },
  {
    id: 'binder-graded',
    name: 'Graded Card Binder album pro 30 PSA/Beckett slabů',
    type: 'accessory',
    game: 'Accessories',
    subcat: 'Binders',
    subsubcat: 'graded',
    price: 1290,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/142827_in_1000x1000.jpg',
    desc: 'Prémiový pořadač na graded karty (PSA/Beckett slabs). Umožňuje bezpečně prezentovat a transportovat 30 ohodnocených slabů v pevných šanonech.',
    stock: 4
  },
  {
    id: 'deck-box-ultimate-guard',
    name: 'Ultimate Guard Deck Case 100+ (Černá krabička)',
    type: 'accessory',
    game: 'Accessories',
    subcat: 'Other',
    price: 99,
    image: 'https://tcgplayer-cdn.tcgplayer.com/product/142827_in_1000x1000.jpg',
    desc: 'Pevná plastová krabička na uložení celého herního balíčku o 100 kartách v double-sleeve obalech.',
    stock: 40
  },

  // --- AKRYLY (Acrylics) ---
  {
    id: 'acrylic-booster-box-pokemon',
    name: 'Akrylový ochranný case pro Pokémon Booster Box',
    type: 'accessory',
    category: 'Acrylics',
    game: 'Pokémon',
    price: 590,
    image: '/acrylic-etb-box.webp',
    desc: 'Prémiový akrylový ochranný case pro standardní Pokémon Booster Box. Tloušťka 4mm, 99% UV ochrana and extra silné magnetické zavírání.',
    stock: 12,
    acrylicThickness: 4,
    uvProtection: true,
    closingType: 'Magnetické víko',
    innerDimensions: '142 x 125 x 78 mm'
  },
  {
    id: 'acrylic-etb-pokemon',
    name: 'Akrylový ochranný box pro Elite Trainer Box',
    type: 'accessory',
    category: 'Acrylics',
    game: 'Pokémon',
    price: 690,
    image: '/acrylic-etb-box.webp',
    desc: 'Prémiový box z vysoce kvalitního 4mm akrylátu s magnetickým víkem a UV ochranou. Navržen speciálně pro dlouhodobou ochranu Pokémon ETB boxů před prachem a poškozením.',
    stock: 15,
    acrylicThickness: 4,
    uvProtection: true,
    closingType: 'Magnetické víko',
    innerDimensions: '193 x 171 x 92 mm'
  },
  {
    id: 'acrylic-trove-box-lorcana',
    name: 'Akrylový ochranný case pro Lorcana Trove',
    type: 'accessory',
    category: 'Acrylics',
    game: 'Lorcana',
    price: 790,
    image: '/acrylic-etb-box.webp',
    desc: 'Prémiový akrylový ochranný case pro Lorcana Illumineer\'s Trove boxy. Tloušťka 4mm, 99% UV ochrana and magnetické víko pro bezpečnost Vaší investice.',
    stock: 5,
    acrylicThickness: 4,
    uvProtection: true,
    closingType: 'Magnetické víko',
    innerDimensions: '165 x 105 x 130 mm'
  },
  {
    id: 'acrylic-booster-box-riftbound',
    name: 'Akrylový ochranný case pro Riftbound Booster Box',
    type: 'accessory',
    category: 'Acrylics',
    game: 'Riftbound',
    price: 590,
    image: '/acrylic-etb-box.webp',
    desc: 'Prémiový ochranný case na Riftbound Booster boxy z 4mm akrylu s magnetickým uzávěrem a ochranou proti UV záření.',
    stock: 6,
    acrylicThickness: 4,
    uvProtection: true,
    closingType: 'Magnetické víko',
    innerDimensions: '145 x 130 x 80 mm'
  },
  {
    id: 'acrylic-psa-stand',
    name: 'Akrylový stojánek pro graded PSA karty',
    type: 'accessory',
    category: 'Acrylics',
    game: 'PSA',
    price: 190,
    image: '/acrylic-etb-box.webp',
    desc: 'Akrylový stojánek a ochranné pouzdro pro graded karty od společnosti PSA. Zabezpečí vaši investiční kartu na poličce a ochrání ji před UV zářením.',
    stock: 25,
    acrylicThickness: 3,
    uvProtection: true,
    closingType: 'Nasouvací systém',
    innerDimensions: '85 x 137 x 10 mm'
  },

  // --- SLABS (Graded Cards) ---
  {
    id: 'slab-charizard-psa10',
    name: 'Charizard ex 223/197 - PSA 10 Gem Mint',
    type: 'slab',
    game: 'Pokémon',
    edition: 'Obsidian Flames',
    price: 4900,
    subsubcategory: 'Grade 10 Gem Mint',
    company: 'PSA',
    grade: 10,
    certNumber: '89423189',
    image: 'https://images.pokemontcg.io/sv3/223.png',
    backImage: 'https://images.pokemontcg.io/unbroken_bonds/back.png',
    desc: 'Certifikovaná karta v pouzdře PSA s nejvyšším možným hodnocením 10 Gem Mint. Bezchybná centrace, hrany i povrch.',
    stock: 1
  },
  {
    id: 'slab-pikachu-bgs95',
    name: 'Pikachu VMAX 188/185 - Beckett 9.5 Gem Mint',
    type: 'slab',
    game: 'Pokémon',
    edition: 'Vivid Voltage',
    price: 6200,
    subsubcategory: 'Grade 9.5 Mint',
    company: 'Beckett',
    grade: 9.5,
    certNumber: '10048291',
    image: 'https://images.pokemontcg.io/swsh4/188.png',
    backImage: 'https://images.pokemontcg.io/unbroken_bonds/back.png',
    desc: 'Certifikovaná karta v pouzdře Beckett (BGS) se známkou 9.5 Gem Mint. Sub-grades: Centering 9.5, Edges 9.5, Corners 9.5, Surface 10.',
    stock: 1
  },
  {
    id: 'slab-umbreon-psa10',
    name: 'Umbreon VMAX 215/203 - PSA 10 Gem Mint',
    type: 'slab',
    game: 'Pokémon',
    edition: 'Evolving Skies',
    price: 38900,
    subsubcategory: 'Grade 10 Gem Mint',
    company: 'PSA',
    grade: 10,
    certNumber: '92184310',
    image: 'https://images.pokemontcg.io/swsh7/215.png',
    backImage: 'https://images.pokemontcg.io/unbroken_bonds/back.png',
    desc: 'Certifikovaná karta v pouzdře PSA s nejvyšším možným hodnocením 10 Gem Mint. Legendární Moonbreon.',
    stock: 1
  },
  {
    id: 'slab-giratina-psa10',
    name: 'Giratina V 186/196 - PSA 10 Gem Mint',
    type: 'slab',
    game: 'Pokémon',
    edition: 'Lost Origin',
    price: 18900,
    subsubcategory: 'Grade 10 Gem Mint',
    company: 'PSA',
    grade: 10,
    certNumber: '75429188',
    image: 'https://images.pokemontcg.io/swsh11/186.png',
    backImage: 'https://images.pokemontcg.io/unbroken_bonds/back.png',
    desc: 'Certifikovaná karta v pouzdře PSA s nejvyšším možným hodnocením 10 Gem Mint. Nádherný kus s dokonalým stavem.',
    stock: 1
  },
  {
    id: 'slab-lugia-psa10',
    name: 'Lugia V 186/195 - PSA 10 Gem Mint',
    type: 'slab',
    game: 'Pokémon',
    edition: 'Silver Tempest',
    price: 11900,
    subsubcategory: 'Grade 10 Gem Mint',
    company: 'PSA',
    grade: 10,
    certNumber: '68421990',
    image: 'https://images.pokemontcg.io/swsh12/186.png',
    backImage: 'https://images.pokemontcg.io/unbroken_bonds/back.png',
    desc: 'Certifikovaná karta v pouzdře PSA s nejvyšším možným hodnocením 10 Gem Mint. Vyhledávaná alternativní ilustrace Lugia V.',
    stock: 1
  }
];

export const bulkRates = [
  { id: '1', game: 'Pokémon', type: 'Common / Uncommon', cashRate: 0.3, creditRate: 0.38 },
  { id: '2', game: 'Pokémon', type: 'Rare / Holo Rare', cashRate: 1.5, creditRate: 1.88 },
  { id: '3', game: 'Pokémon', type: 'Ultra Rare (ex/V/VMAX)', cashRate: 10.0, creditRate: 12.5 },
  { id: '4', game: 'Lorcana', type: 'Legendary / Rare', cashRate: 3.0, creditRate: 3.75 },
  { id: '5', game: 'One Piece', type: 'Common / Uncommon / Leader', cashRate: 0.2, creditRate: 0.25 }
];
